# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33a1b1761c6109c90572818e6abe4e66e0e8acc2d39e608fde1a44d70657d3cbcccf2f57bb4fde364a239e34da5748b80b50205e50c8350aedb40ad2a4b543b6

test:
  secret_key_base: 46194d629be5d3d50e4a00a099d8cb75f349a315ea92624dbfc21b72ae70c513b80698e03f44ecbf7993b059d270505946f643fd879ec3b3834630872998417f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
